# Classification with SVM. Social Network dataset

```{r setup, include = FALSE, error=TRUE, message=FALSE, warning=FALSE} 
knitr::opts_chunk$set(echo = TRUE, 
                      comment = "#>", 
                      error = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.align = 'center')
```

```{r echo=FALSE}
load(file.path(rprojroot::find_rstudio_root_file(), "workspace.RData"))
.libPaths(c(normalizePath(sbox_path), normalizePath(lib_path), .libPaths()))
```

## Introduction

## Data Operations

### Load libraries

```{r warning=FALSE, message=FALSE}
# load packages
library(dplyr)
library(caTools) 
library(e1071) 
library(ElemStatLearn) 
```

### Importing dataset

```{r}
# Importing the dataset 
dataset = read.csv(file.path(data_raw_dir, 'Social_Network_Ads.csv')) 
dplyr::glimpse(dataset)
```

```{r}
tibble::as_tibble(dataset)
```

```{r}
# Taking columns 3-5 
dataset = dataset[3:5]
tibble::as_tibble(dataset)
```


```{r}
# Encoding the target feature as factor 
dataset$Purchased = factor(dataset$Purchased, levels = c(0, 1)) 
str(dataset)
```

```{r}
# Splitting the dataset into the Training set and Test set 
set.seed(123) 
split = sample.split(dataset$Purchased, SplitRatio = 0.75) 
  
training_set = subset(dataset, split == TRUE) 
test_set = subset(dataset, split == FALSE) 
```

```{r}
dim(training_set)
dim(test_set)
```

```{r}
# Feature Scaling 
training_set[-3] = scale(training_set[-3]) 
test_set[-3] = scale(test_set[-3]) 
```

```{r}
# Fitting SVM to the Training set 
classifier = svm(formula = Purchased ~ ., 
                 data = training_set, 
                 type = 'C-classification', 
                 kernel = 'linear') 
```

```{r}
classifier
```

```{r}
summary(classifier)
```

```{r}
# Predicting the Test set results 
y_pred = predict(classifier, newdata = test_set[-3]) 
y_pred
```

```{r}
# Making the Confusion Matrix 
cm = table(test_set[, 3], y_pred) 
cm
```

```{r}
xtable::xtable(cm)
```

```{r plot_training_set, fig.width=5, fig.height=5}
# installing library ElemStatLearn 
# library(ElemStatLearn) 
  
# Plotting the training data set results 
set = training_set 
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01) 
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01) 
  
grid_set = expand.grid(X1, X2) 
colnames(grid_set) = c('Age', 'EstimatedSalary') 
y_grid = predict(classifier, newdata = grid_set) 
  
plot(set[, -3], 
     main = 'SVM (Training set)', 
     xlab = 'Age', ylab = 'Estimated Salary', 
     xlim = range(X1), ylim = range(X2)) 
  
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE) 
  
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'coral1', 'aquamarine')) 
  
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3')) 

```

```{r}
set = test_set 
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01) 
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01) 
  
grid_set = expand.grid(X1, X2) 
colnames(grid_set) = c('Age', 'EstimatedSalary') 
y_grid = predict(classifier, newdata = grid_set) 
  
plot(set[, -3], main = 'SVM (Test set)', 
     xlab = 'Age', ylab = 'Estimated Salary', 
     xlim = range(X1), ylim = range(X2)) 
  
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE) 
  
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'coral1', 'aquamarine')) 
  
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3')) 

```

