
Source: https://www.hackerearth.com/fr/practice/machine-learning/machine-learning-algorithms/understanding-deep-learning-parameter-tuning-with-mxnet-h2o-package-in-r/tutorial/

```{r echo=FALSE}
load(file.path(rprojroot::find_rstudio_root_file(), "workspace.RData"))
.libPaths(c(normalizePath(sbox_path), normalizePath(lib_path), .libPaths()))
```

```{r}
#load libraries
library(data.table)
library(mlr)

#set variable names
setcol <- c("age",
           "workclass",
           "fnlwgt",
           "education",
           "education-num",
           "marital-status",
           "occupation",
           "relationship",
           "race",
           "sex",
           "capital-gain",
           "capital-loss",
           "hours-per-week",
           "native-country",
           "target")

#load data
train <- read.table(file.path(data_raw_dir, "adult.data.txt"), header = F, sep = ",", 
                    col.names = setcol, na.strings = c(" ?"), stringsAsFactors = F)
test <- read.table(file.path(data_raw_dir, "adult.test.txt"), header = F,sep = ",", 
                   col.names = setcol, skip = 1, na.strings = c(" ?"), stringsAsFactors = F)

setDT(train)
setDT(test)

#Data Sanity
dim(train)
# [1] 32561 X 15

dim(test)
# [1] 16281 X 15

str(train)
str(test)

#check missing values
table(is.na(train))
sapply(train, function(x) sum(is.na(x))/length(x))*100
table(is.na(test))
sapply(test, function(x) sum(is.na(x))/length(x))*100

#check target variable
#binary in nature check if data is imbalanced
train[,.N/nrow(train),target]
test[,.N/nrow(test),target]

#remove extra characters
test[,target := substr(target,start = 1,stop = nchar(target)-1)]

#remove leading whitespace
library(stringr)
char_col <- colnames(train)[sapply(test,is.character)]

for(i in char_col) set(train,j=i,value = str_trim(train[[i]],side = "left"))

#set all character variables as factor
fact_col <- colnames(train)[sapply(train,is.character)]

for(i in fact_col) set(train,j=i,value = factor(train[[i]]))
for(i in fact_col) set(test,j=i,value = factor(test[[i]]))


```

```{r}
df = data.frame(x = c(1, 1, NA), y = factor(c("a", "a", "b")), z = 1:3)
imputed = impute(df, target = character(0), cols = list(x = 99, y = imputeMode()))
print(imputed$data)
reimpute(data.frame(x = NA_real_), imputed$desc)
```
```{r}
str(train)
```


```{r}
#impute missing values
imp1 <- impute(train, target = "target", classes = list(integer = imputeMedian(), 
                                                               factor = imputeMode()))
imp2 <- impute(test, target = "target", classes = list(integer = imputeMedian(), 
                                                              factor = imputeMode()))

train <- setDT(imp1$data)
test <- setDT(imp2$data)
```




```{r}

```



```{r}

```

